# Generated by Django 4.2.1 on 2023-06-20 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requirements',
            options={'verbose_name_plural': 'Requirements'},
        ),
    ]
